env: foraging

env_args:
  field_size: [10,10]
  players: 4
  max_food: 2
  force_coop: False
  max_episode_steps: 50
  max_player_level: 2
  sight: 2
  episode_limit: 100000

learner_log_interval: 10000
log_interval: 10000
runner_log_interval: 10000
t_max: 2050000
test_interval: 10000
test_nepisode: 40
episode_limit: 100000
